apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-exporter
  namespace: linkding
  labels:
    release: prom-stack
spec:
  selector:
    matchLabels:
      app: postgres
  endpoints:
    - port: exporter
      interval: 30s
