apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: linkding
  labels:
    app: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9187'
        prometheus.io/path: '/metrics'
        summary: 'Linkding Postgres Exporter'
    spec:
      serviceAccountName: postgres
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        runAsNonRoot: true
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 60 # Give postgres time to shut down gracefully
      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            # PostgreSQL performance tuning
            - name: POSTGRES_INITDB_ARGS
              value: '--auth-host=scram-sha-256'
            - name: POSTGRES_HOST_AUTH_METHOD
              value: 'scram-sha-256'
          resources:
            requests:
              memory: '256Mi'
              cpu: '100m'
            limits:
              memory: '512Mi'
              cpu: '500m'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false # PostgreSQL needs write access
            capabilities:
              drop:
                - ALL
              add:
                - CHOWN
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -h localhost -U "$POSTGRES_USER" -d "$POSTGRES_DB"
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
        - name: postgres-exporter
          image: prometheuscommunity/postgres-exporter:v0.15.0
          imagePullPolicy: IfNotPresent
          args:
            - --extend.query-path=/tmp/postgres_exporter.yml
          ports:
            - containerPort: 9187
              name: metrics
              protocol: TCP
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATA_SOURCE_URI
              value: 'localhost:5432/linkding?sslmode=disable'
          volumeMounts:
            - name: exporter-config
              mountPath: /tmp/postgres_exporter.yml
              subPath: postgres_exporter.yml
              readOnly: true
          resources:
            requests:
              memory: '32Mi'
              cpu: '10m'
            limits:
              memory: '64Mi'
              cpu: '50m'
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534 # nobody
            runAsGroup: 65534
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9187
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
      volumes:
        - name: exporter-config
          configMap:
            name: postgres-exporter-config
            items:
              - key: postgres_exporter.yml
                path: postgres_exporter.yml
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkding
  labels:
    app: postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
    - name: exporter
      port: 9187
      targetPort: 9187
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
  namespace: linkding
  labels:
    app: postgres
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: linkding
spec:
  schedule: '0 19 * * *' # 8 PM CET (winter) / 9 PM CEST (summer) - Good time for backups after peak hours
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: postgres-backup
        spec:
          serviceAccountName: postgres-backup
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
          containers:
            - name: backup
              image: postgres:16-alpine
              imagePullPolicy: IfNotPresent
              env:
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_USER
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_DB
                - name: POSTGRES_HOST
                  value: postgres-read
                - name: BACKUP_RETENTION_DAYS
                  value: '7' # Keep 7 days of backups
              command:
                - /bin/sh
                - -c
                - |
                  set -euo pipefail
                  BACKUP_DIR="/var/lib/postgresql/backups"
                  mkdir -p "$BACKUP_DIR"
                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="$BACKUP_DIR/linkding_backup_$TIMESTAMP.sql.gz"

                  echo "Starting backup at $(date)"
                  if pg_dump -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$POSTGRES_DB" | gzip > "$BACKUP_FILE"; then
                    BACKUP_SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
                    echo "Backup completed successfully: $BACKUP_FILE (Size: $BACKUP_SIZE)"
                    
                    # Verify backup integrity
                    if gzip -t "$BACKUP_FILE" 2>/dev/null; then
                      echo "Backup integrity verified"
                    else
                      echo "ERROR: Backup file is corrupted!" >&2
                      rm -f "$BACKUP_FILE"
                      exit 1
                    fi
                    
                    # Cleanup old backups (keep last N days)
                    find "$BACKUP_DIR" -name "linkding_backup_*.sql.gz" -type f -mtime +$BACKUP_RETENTION_DAYS -delete
                    echo "Old backups cleaned up (retention: $BACKUP_RETENTION_DAYS days)"
                  else
                    echo "ERROR: Backup failed!" >&2
                    exit 1
                  fi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false # Need to write backups
                capabilities:
                  drop:
                    - ALL
              resources:
                requests:
                  memory: '128Mi'
                  cpu: '50m'
                limits:
                  memory: '256Mi'
                  cpu: '100m'
              volumeMounts:
                - name: postgres-backup
                  mountPath: /var/lib/postgresql/backups
          volumes:
            - name: postgres-backup
              persistentVolumeClaim:
                claimName: postgres-backup-pvc
          restartPolicy: OnFailure
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: linkding
spec:
  minAvailable: 0 # Allow disruption since we only have 1 replica
  selector:
    matchLabels:
      app: postgres
