apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9187"
        prometheus.io/path: "/metrics"
        summary: "Linkding Postgres Exporter"
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -h localhost -U linkding
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -h localhost -U linkding
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      - name: postgres-exporter
        image: prometheuscommunity/postgres-exporter:v0.15.0
        args:
        - --config.file=/etc/postgres_exporter.yml
        ports:
        - containerPort: 9187
        env:
        - name: DATA_SOURCE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DATA_SOURCE_PASS
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATA_SOURCE_URI
          value: "postgresql://postgres:5432/postgres?sslmode=disable"
        volumeMounts:
        - name: exporter-config
          mountPath: /etc/postgres_exporter.yml
          subPath: postgres_exporter.yml
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "50m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
      - name: exporter-config
        configMap:
          name: postgres-exporter-config
          items:
          - key: postgres_exporter.yml
            path: postgres_exporter.yml
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkding
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  - name: exporter
    port: 9187
    targetPort: 9187
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: linkding
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          containers:
          - name: backup
            image: postgres:16-alpine
            env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            command:
            - /bin/sh
            - -c
            - |
              BACKUP_DIR="/var/lib/postgresql/backups"
              mkdir -p $BACKUP_DIR
              TIMESTAMP=$(date +%Y%m%d_%H%M%S)
              pg_dump -h postgres -U linkding linkding | gzip > $BACKUP_DIR/linkding_backup_$TIMESTAMP.sql.gz
              ls -t $BACKUP_DIR/linkding_backup_*.sql.gz | tail -n +8 | xargs rm -f
              echo "Backup completed: linkding_backup_$TIMESTAMP.sql.gz"
            resources:
              requests:
                memory: "128Mi"
                cpu: "50m"
              limits:
                memory: "256Mi"
                cpu: "100m"
            volumeMounts:
            - name: postgres-backup
              mountPath: /var/lib/postgresql/backups
          volumes:
          - name: postgres-backup
            persistentVolumeClaim:
              claimName: postgres-backup-pvc
          restartPolicy: OnFailure