apiVersion: v1
kind: ServiceAccount
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: linkding
  labels:
    app: postgres
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-backup
  namespace: linkding
  labels:
    app: postgres-backup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ldhc
  namespace: linkding
  labels:
    app: ldhc
