# Horizontal Pod Autoscaler for Linkding
# Requires metrics-server to be installed
# Only enable if you need auto-scaling
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: linkding-hpa
  namespace: linkding
  labels:
    app: linkding
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkding
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
      selectPolicy: Max
