# Linkding Health Check (LDHC) CronJob
# Automatically checks bookmarks for broken links and duplicates
# Requires linkding-api-secret with API_TOKEN key
# See: https://github.com/sebw/linkding-healthcheck
apiVersion: batch/v1
kind: CronJob
metadata:
  name: linkding-healthcheck
  namespace: linkding
  labels:
    app: linkding-healthcheck
spec:
  schedule: '0 20 * * 0'  # Sunday at 8 PM (adjust for your timezone)
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: linkding-healthcheck
        spec:
          serviceAccountName: linkding
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
          containers:
            - name: ldhc
              image: ghcr.io/sebw/linkding-healthcheck:latest
              imagePullPolicy: Always
              env:
                - name: API_URL
                  # Internal cluster traffic - HTTP is safe for pod-to-pod communication
                  value: 'http://linkding:9090'
                - name: API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: linkding-api-secret
                      key: API_TOKEN
                - name: CHECK_DUPLICATES
                  value: 'true'
                - name: CHECK_URLS
                  value: 'true'
                - name: TIMEOUT
                  value: '10'
              resources:
                requests:
                  memory: '64Mi'
                  cpu: '25m'
                limits:
                  memory: '128Mi'
                  cpu: '100m'
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                capabilities:
                  drop:
                    - ALL
          restartPolicy: OnFailure
