# Gateway API HTTPRoute for Linkding
# Requires Gateway API and Istio installed
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  parentRefs:
    - name: cluster-gateway
      namespace: istio-system
  hostnames:
    - "linkding.k8s.local"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: linkding
          port: 9090
