apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: linkding
type: Opaque
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:/cn0HZqKgDI=,iv:xOMHp3KDvGvvBXvrfiiibnLT7UNPqsQOK5MHKb5xJMU=,tag:VJVAb7ZS/vPQDYT8c5YSzg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:K5TR9yJF8Vs=,iv:ym5QWwUQzsIIUnojew0qtQ424u6Djvccy2HqrTJYPr4=,tag:SFEdbuhTmsrGO5hbi+NGWA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:5Oym7VXQHck=,iv:kSPkbCRbip6uLP6RGVcxKDqDDudE4j3UL0TbTHQfsOc=,tag:Ir34RmkOXmBjZaMY4MpnJA==,type:str]
sops:
    age:
        - recipient: age1tyqgw9lv8r7p2ewjznt8rw8050ysp63vletzy2w3hxfa7dzqdu6qdqwsl4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWG0xV1FFRkRaVTZvQ3Q5
            MHd1WUxUQ3pWM2hYeWhUcnNubm1vZlVFd2t3Ck1Qb3VnTkJaTUtNQWpRVHA5U0J2
            MFdHdmJKQjVIcTZQMGsvWXRpblVYdjAKLS0tIGVvbm9KcUZndEJ5Q1hBYjllQ1B3
            cDFhcVZVZEZ6N2lOTWZBbklvTG9jTzgKfYAoxe5KSFCzu4ny0YQjH0mgjqSBjtnJ
            oKcBp9BO1wbfkqsBUO0vK8pnArXs9zStsfHD9G3MQfh6zmzHIkDu3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-14T14:31:12Z"
    mac: ENC[AES256_GCM,data:Lcj0M1LxSVH7/bUHf+n+ILdwpb0Bn8MxaGQHc7PABPjAJRiNnmF9Tyjmz5pG2xIeSjuhHDVna8e10uKsA73YIDdOUe/Pe/G75WXiE2SyAJzxiFxvneDUaYFJJBl6Kh8ABdMwI7pTeFLw13kAjvWfvPO1J/U3a6hd4tBjjsukAE4=,iv:6iSpovJ6xgKTSRLLVI7btXiRY0wiXetOfaA5DU8iTFE=,tag:KYLj9XEPmLp2W7ABpbDaeg==,type:str]
    encrypted_regex: ^(data|stringData|password|token|key|secret|apiKey|apiToken|credential)$
    version: 3.11.0
